Patch the init container with compute resources
k8tz/k8tz pull request #85
Opened 2023-09-19 01:37 UTC by feizhe1996

Fix for https://github.com/k8tz/k8tz/issues/83.
Previously, the compute resources specified in values.yaml did not get passed down to the initContainer specs. When the namespace is guarded by a resource quota, each container needs to specify the resource requirement, otherwise, k8s throws quota errors.

Since the resources definition is a multi-line string block, the fix tries to pass a json formatted string as an argument to the cli.

2023-09-19 01:38 UTC, feizhe1996 commented
cc: @yonatankahana for review

2023-10-12 20:01 UTC, yonatankahana requested changes

2024-03-29 10:59 UTC, yonatankahana commented
ping @feizhe1996

2024-04-22 22:07 UTC, feizhe1996 commented
> ping @feizhe1996

Ack

2024-04-23 16:58 UTC, feizhe1996 commented
Ping @yonatankahana  for review

2024-05-23 16:28 UTC, feizhe1996 commented
ping @yonatankahana for review

2024-05-30 08:02 UTC, jiriksykora commented
we are still waiting for mr

2024-05-31 06:05 UTC, feizhe1996 commented
> we are still waiting for mr

ping @yonatankahana  again

2024-05-31 13:13 UTC, yonatankahana requested changes
hi, sorry for my late responses. please fix this small things and let's release it this weekend.

2024-05-31 13:13 UTC, yonatankahana commented on charts/k8tz/values.yaml
> +resources: {} # resources claimed for the k8tz controller
resources already exist in `values.yaml`

2024-05-31 13:13 UTC, yonatankahana commented on charts/k8tz/values.yaml
> +initContainerResources: {} # resources claimed for the bootstrap init container
please document the new value in the chart README.md

2024-06-01 00:58 UTC, feizhe1996 commented
Commit updated cc: @yonatankahana

2024-06-01 18:07 UTC, merged